### ISSUE TITLE
Repair PrimaryController.switchToSecondary() and SecondaryController.switchToPrimary()

### ISSUE THREAD

**Issue by lingocoder** [Geek8080/Daily-Journal#3]
The very first (*and only*) thing I did immediately after downloading this project was run *`mvn verify`*. The project failed to build…

```
$ mvn verify
…
[ERROR] .../Daily-Journal-master/Diary/src/main/java/org/geek8080/journal/main/SecondaryController.java:[10,12] cannot find symbol
  symbol:   method setRoot(java.lang.String)
  location: class org.geek8080.journal.main.App
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Daily-Journal 1.0:
[INFO]
[INFO] Daily-Journal ...................................... SUCCESS [  0.015 s]
[INFO] Entities ........................................... SUCCESS [ 32.946 s]
[INFO] Utils .............................................. SUCCESS [  5.389 s]
[INFO] Services ........................................... SUCCESS [01:34 min]
[INFO] Diary .............................................. FAILURE [ 48.064 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
…
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Diary: Compilation failure: Compilation failure:
[ERROR] …/Daily-Journal-master/Diary/src/main/java/org/geek8080/journal/main/PrimaryController.java:[10,12] cannot find symbol
[ERROR]   symbol:   method setRoot(java.lang.String)
[ERROR]   location: class org.geek8080.journal.main.App
[ERROR] …/Daily-Journal-master/Diary/src/main/java/org/geek8080/journal/main/SecondaryController.java:[10,12] cannot find symbol
[ERROR]   symbol:   method setRoot(java.lang.String)
[ERROR]   location: class org.geek8080.journal.main.App

```
The error message reports that [*`PrimaryController.switchToSecondary()`*](https://github.com/Geek8080/Daily-Journal/blob/master/Diary/src/main/java/org/geek8080/journal/main/PrimaryController.java#L10) and [*`SecondaryController.switchToPrimary()`*](https://github.com/Geek8080/Daily-Journal/blob/master/Diary/src/main/java/org/geek8080/journal/main/SecondaryController.java#L10) both call a non-existent *`App.setRoot(String)`* method. 

Your project [*uses JavaFX 14*](https://github.com/Geek8080/Daily-Journal/blob/master/Diary/pom.xml#L20). Your *`App`* class extends [*`javafx.application.Application`*](https://openjfx.io/javadoc/14/javafx.graphics/javafx/application/Application.html). But *`javafx.application.Application`* does not define a *`setRoot(String)`* method.

## Steps to reproduce

1. Download the project
2. *`cd`* to the root folder of the project
3. Run *`mvn verify`*

**Comment by Geek8080** [comment]
These files were no longer required. Forgot to commit the deletion I made at the starting of this project. Deleting it fixed the issue. Closing the issue.
